"""Packs every sounds/*.wav into sounds/sounds_pack.js.

Browsers refuse to fetch() local files when the game is opened by double-clicking
the HTML (file://). A <script> tag still works there, so the game falls back to
this pack. Run this (or pack_sounds.bat) after adding or editing a .wav file.
"""
import base64
import pathlib

root = pathlib.Path(__file__).resolve().parent.parent
sounds = root / "sounds"
files = sorted(sounds.glob("*.wav"))
lines = ["// Generated by tools/pack_sounds.py - do not edit, edit the .wav files instead.",
         "window.SOUND_PACK = {"]
for f in files:
    lines.append(f'  "{f.stem}": "{base64.b64encode(f.read_bytes()).decode()}",')
lines.append("};")
(sounds / "sounds_pack.js").write_text("\n".join(lines) + "\n", encoding="utf-8")
print(f"Packed {len(files)} sounds into sounds/sounds_pack.js")
